# Sample Harness pipeline (conceptual) to build and deploy the Vite app to S3.
# You will need to adapt connectors, secrets, and steps to your Harness account.

pipeline:
  name: Deploy React App to S3
  identifier: deploy_react_app_s3
  stages:
    - stage:
        name: BuildAndDeploy
        identifier: build_and_deploy
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  spec:
                    shell: POWERSHELL
                    command: |
                      npm ci
              - step:
                  type: Run
                  name: Build
                  spec:
                    shell: POWERSHELL
                    command: |
                      npm run build
              - step:
                  type: Run
                  name: Deploy to S3
                  spec:
                    shell: POWERSHELL
                    # Ensure AWS credentials are provided in the environment
                    command: |
                      .\scripts\deploy-to-s3.ps1 -BucketName $env:S3_BUCKET_NAME -Region $env:AWS_REGION
